/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MinesGame {
  export type RoundStruct = {
    player: AddressLike;
    stake: BigNumberish;
    mineCount: BigNumberish;
    vrfSeed: BigNumberish;
    vrfRequestId: BigNumberish;
    status: BigNumberish;
    safePicks: BigNumberish;
    multiplier100: BigNumberish;
    netPayout: BigNumberish;
    createdAt: BigNumberish;
    settledAt: BigNumberish;
    custodial: boolean;
  };

  export type RoundStructOutput = [
    player: string,
    stake: bigint,
    mineCount: bigint,
    vrfSeed: bigint,
    vrfRequestId: bigint,
    status: bigint,
    safePicks: bigint,
    multiplier100: bigint,
    netPayout: bigint,
    createdAt: bigint,
    settledAt: bigint,
    custodial: boolean
  ] & {
    player: string;
    stake: bigint;
    mineCount: bigint;
    vrfSeed: bigint;
    vrfRequestId: bigint;
    status: bigint;
    safePicks: bigint;
    multiplier100: bigint;
    netPayout: bigint;
    createdAt: bigint;
    settledAt: bigint;
    custodial: boolean;
  };
}

export interface MinesGameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BOARD_SIZE"
      | "DEFAULT_ADMIN_ROLE"
      | "GAME_ID"
      | "OPERATOR_ROLE"
      | "UPGRADER_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "activeRound"
      | "cashout"
      | "cashoutFor"
      | "fulfillRandomness"
      | "gameId"
      | "gameName"
      | "getMinePositions"
      | "getRoleAdmin"
      | "getRound"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "loseRound"
      | "loseRoundFor"
      | "maxMines"
      | "maxStake"
      | "minStake"
      | "pause"
      | "paused"
      | "proxiableUUID"
      | "randomness"
      | "refundPending"
      | "renounceRole"
      | "revokeRole"
      | "rounds"
      | "setLimits"
      | "startRound"
      | "startRoundFor"
      | "supportsInterface"
      | "treasury"
      | "unpause"
      | "upgradeToAndCall"
      | "vrfToRound"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "RoundActive"
      | "RoundCashedOut"
      | "RoundLost"
      | "RoundRefunded"
      | "RoundStarted"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BOARD_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "GAME_ID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeRound",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cashout",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cashoutFor",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillRandomness",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "gameId", values?: undefined): string;
  encodeFunctionData(functionFragment: "gameName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMinePositions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getRound", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loseRound",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loseRoundFor",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "maxMines", values?: undefined): string;
  encodeFunctionData(functionFragment: "maxStake", values?: undefined): string;
  encodeFunctionData(functionFragment: "minStake", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "randomness",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundPending",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "rounds", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setLimits",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startRound",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startRoundFor",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vrfToRound",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "BOARD_SIZE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "GAME_ID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cashout", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cashoutFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gameName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMinePositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRound", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loseRound", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loseRoundFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxMines", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "randomness", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setLimits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startRound", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startRoundFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vrfToRound", data: BytesLike): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundActiveEvent {
  export type InputTuple = [roundId: BytesLike, vrfSeed: BigNumberish];
  export type OutputTuple = [roundId: string, vrfSeed: bigint];
  export interface OutputObject {
    roundId: string;
    vrfSeed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundCashedOutEvent {
  export type InputTuple = [
    roundId: BytesLike,
    player: AddressLike,
    safePicks: BigNumberish,
    multiplier100: BigNumberish,
    netPayout: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    roundId: string,
    player: string,
    safePicks: bigint,
    multiplier100: bigint,
    netPayout: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    roundId: string;
    player: string;
    safePicks: bigint;
    multiplier100: bigint;
    netPayout: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundLostEvent {
  export type InputTuple = [
    roundId: BytesLike,
    player: AddressLike,
    hitTile: BigNumberish
  ];
  export type OutputTuple = [roundId: string, player: string, hitTile: bigint];
  export interface OutputObject {
    roundId: string;
    player: string;
    hitTile: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundRefundedEvent {
  export type InputTuple = [roundId: BytesLike, player: AddressLike];
  export type OutputTuple = [roundId: string, player: string];
  export interface OutputObject {
    roundId: string;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundStartedEvent {
  export type InputTuple = [
    roundId: BytesLike,
    player: AddressLike,
    stake: BigNumberish,
    mineCount: BigNumberish,
    vrfRequestId: BigNumberish
  ];
  export type OutputTuple = [
    roundId: string,
    player: string,
    stake: bigint,
    mineCount: bigint,
    vrfRequestId: bigint
  ];
  export interface OutputObject {
    roundId: string;
    player: string;
    stake: bigint;
    mineCount: bigint;
    vrfRequestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MinesGame extends BaseContract {
  connect(runner?: ContractRunner | null): MinesGame;
  waitForDeployment(): Promise<this>;

  interface: MinesGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BOARD_SIZE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GAME_ID: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADER_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  activeRound: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  cashout: TypedContractMethod<
    [roundId: BytesLike, revealedTiles: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  cashoutFor: TypedContractMethod<
    [roundId: BytesLike, revealedTiles: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  fulfillRandomness: TypedContractMethod<
    [vrfRequestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  gameId: TypedContractMethod<[], [string], "view">;

  gameName: TypedContractMethod<[], [string], "view">;

  getMinePositions: TypedContractMethod<
    [roundId: BytesLike],
    [bigint[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getRound: TypedContractMethod<
    [roundId: BytesLike],
    [MinesGame.RoundStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      admin: AddressLike,
      treasury_: AddressLike,
      randomness_: AddressLike,
      min_: BigNumberish,
      max_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  loseRound: TypedContractMethod<
    [roundId: BytesLike, hitTile: BigNumberish],
    [void],
    "nonpayable"
  >;

  loseRoundFor: TypedContractMethod<
    [roundId: BytesLike, hitTile: BigNumberish],
    [void],
    "nonpayable"
  >;

  maxMines: TypedContractMethod<[], [bigint], "view">;

  maxStake: TypedContractMethod<[], [bigint], "view">;

  minStake: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  randomness: TypedContractMethod<[], [string], "view">;

  refundPending: TypedContractMethod<
    [roundId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  rounds: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        player: string;
        stake: bigint;
        mineCount: bigint;
        vrfSeed: bigint;
        vrfRequestId: bigint;
        status: bigint;
        safePicks: bigint;
        multiplier100: bigint;
        netPayout: bigint;
        createdAt: bigint;
        settledAt: bigint;
        custodial: boolean;
      }
    ],
    "view"
  >;

  setLimits: TypedContractMethod<
    [min_: BigNumberish, max_: BigNumberish, maxM: BigNumberish],
    [void],
    "nonpayable"
  >;

  startRound: TypedContractMethod<
    [stake: BigNumberish, mineCount: BigNumberish],
    [string],
    "nonpayable"
  >;

  startRoundFor: TypedContractMethod<
    [player: AddressLike, stake: BigNumberish, mineCount: BigNumberish],
    [string],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  vrfToRound: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BOARD_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GAME_ID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeRound"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "cashout"
  ): TypedContractMethod<
    [roundId: BytesLike, revealedTiles: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cashoutFor"
  ): TypedContractMethod<
    [roundId: BytesLike, revealedTiles: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fulfillRandomness"
  ): TypedContractMethod<
    [vrfRequestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gameId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gameName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMinePositions"
  ): TypedContractMethod<[roundId: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRound"
  ): TypedContractMethod<
    [roundId: BytesLike],
    [MinesGame.RoundStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      admin: AddressLike,
      treasury_: AddressLike,
      randomness_: AddressLike,
      min_: BigNumberish,
      max_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "loseRound"
  ): TypedContractMethod<
    [roundId: BytesLike, hitTile: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "loseRoundFor"
  ): TypedContractMethod<
    [roundId: BytesLike, hitTile: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "maxMines"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "randomness"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundPending"
  ): TypedContractMethod<[roundId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rounds"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        player: string;
        stake: bigint;
        mineCount: bigint;
        vrfSeed: bigint;
        vrfRequestId: bigint;
        status: bigint;
        safePicks: bigint;
        multiplier100: bigint;
        netPayout: bigint;
        createdAt: bigint;
        settledAt: bigint;
        custodial: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setLimits"
  ): TypedContractMethod<
    [min_: BigNumberish, max_: BigNumberish, maxM: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startRound"
  ): TypedContractMethod<
    [stake: BigNumberish, mineCount: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startRoundFor"
  ): TypedContractMethod<
    [player: AddressLike, stake: BigNumberish, mineCount: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "vrfToRound"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoundActive"
  ): TypedContractEvent<
    RoundActiveEvent.InputTuple,
    RoundActiveEvent.OutputTuple,
    RoundActiveEvent.OutputObject
  >;
  getEvent(
    key: "RoundCashedOut"
  ): TypedContractEvent<
    RoundCashedOutEvent.InputTuple,
    RoundCashedOutEvent.OutputTuple,
    RoundCashedOutEvent.OutputObject
  >;
  getEvent(
    key: "RoundLost"
  ): TypedContractEvent<
    RoundLostEvent.InputTuple,
    RoundLostEvent.OutputTuple,
    RoundLostEvent.OutputObject
  >;
  getEvent(
    key: "RoundRefunded"
  ): TypedContractEvent<
    RoundRefundedEvent.InputTuple,
    RoundRefundedEvent.OutputTuple,
    RoundRefundedEvent.OutputObject
  >;
  getEvent(
    key: "RoundStarted"
  ): TypedContractEvent<
    RoundStartedEvent.InputTuple,
    RoundStartedEvent.OutputTuple,
    RoundStartedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "RoundActive(bytes32,uint256)": TypedContractEvent<
      RoundActiveEvent.InputTuple,
      RoundActiveEvent.OutputTuple,
      RoundActiveEvent.OutputObject
    >;
    RoundActive: TypedContractEvent<
      RoundActiveEvent.InputTuple,
      RoundActiveEvent.OutputTuple,
      RoundActiveEvent.OutputObject
    >;

    "RoundCashedOut(bytes32,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RoundCashedOutEvent.InputTuple,
      RoundCashedOutEvent.OutputTuple,
      RoundCashedOutEvent.OutputObject
    >;
    RoundCashedOut: TypedContractEvent<
      RoundCashedOutEvent.InputTuple,
      RoundCashedOutEvent.OutputTuple,
      RoundCashedOutEvent.OutputObject
    >;

    "RoundLost(bytes32,address,uint8)": TypedContractEvent<
      RoundLostEvent.InputTuple,
      RoundLostEvent.OutputTuple,
      RoundLostEvent.OutputObject
    >;
    RoundLost: TypedContractEvent<
      RoundLostEvent.InputTuple,
      RoundLostEvent.OutputTuple,
      RoundLostEvent.OutputObject
    >;

    "RoundRefunded(bytes32,address)": TypedContractEvent<
      RoundRefundedEvent.InputTuple,
      RoundRefundedEvent.OutputTuple,
      RoundRefundedEvent.OutputObject
    >;
    RoundRefunded: TypedContractEvent<
      RoundRefundedEvent.InputTuple,
      RoundRefundedEvent.OutputTuple,
      RoundRefundedEvent.OutputObject
    >;

    "RoundStarted(bytes32,address,uint256,uint8,uint256)": TypedContractEvent<
      RoundStartedEvent.InputTuple,
      RoundStartedEvent.OutputTuple,
      RoundStartedEvent.OutputObject
    >;
    RoundStarted: TypedContractEvent<
      RoundStartedEvent.InputTuple,
      RoundStartedEvent.OutputTuple,
      RoundStartedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
